### ISSUE TITLE
 [FEATURE]:

### ISSUE THREAD

**Issue by Zannoeaze** [Zombies-World-Records/issue-tracker#16]
Why are most of the 3 and 4 player categories gone now? That seems pretty unfair to the players who put in the time to get those records. That takes a lot of skill and dedication to get but now it was for nothing. Shouldn't matter how many people have submitted for it since it's still something impressive and shouldn't be capped at number of players in the game.

**Comment by iiTsMatthew** [comment]
Hi,

Thank you for your report, however this is the incorrect place to ask about it.

Making a ticket in the discord would've gotten a faster response 😁

However, the reason for it was due to the boards being generally, filled up for 1-2 players, and completely dead for 3-4 Player leaderboards.

You may think 3-4P leaderboards seem impressive, but to those of the players that play competitively and on a high level, it is not.

I hope this answers your question 😁

Kind Regards,

Matthew.
