### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by Zannoeaze** [Zombies-World-Records/issue-tracker#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Leaderboards are messed up. Have flawless records higher than normal records with different people. Community is starting to not trust the credibility of this site, just a heads up.

### Expected behaviour

Credibility at stake

### Steps to reproduce

Look at the leaderboards 

### ZWR Account Link

Zannoeaze

**Comment by iiTsMatthew** [comment]
Good Afternoon,

Thank you for the report.

However, I must mention two things to you.

1) this isn't the place to report something like this, in our discord Via tickets is the way to do this.

2) if you're going to mention something like that, stating that 'your credibility is at risk' perhaps, mention which games might be at issue and we can look into them.

Also, I don't understand what you mean by 'flawless records higher than normal records', do you mean there are flawless records higher than non-flawless records?

This also doesn't mean they are technically incorrect, or 'fishy', it might just mean the records you're talking about haven't been pushed and that's why flawless is higher.

Also, saying 'look at the leaderboards' gives us zero ideas where they might be, as you might know, we have over 1000 boards on the site, and simply cannot check every single record on every leaderboard to check what you mean or find your issue.

Please make a ticket on Discord and we can clear this up for you.

Kind Regards,
Matthew.

**Comment by Zannoeaze** [comment]
How is reporting the leaderboards are inaccurate on this site which has the leaderboards not the right place to report it. And as an example I'm talking about how are flawless high round records higher than the non flawless high round record In some areas. Shouldn't they be the same if the flawless is the highest? I've noticed other things with the leaderboards over the last couple months change that don't add up but I can see you don't think anything is wrong which is why the credibility is being questioned by me and many others of the community. If you aren't able to take the time and look at the inconsistencies of the leaderboards than I don't think there's much hope for this site with the people running it anymore

**Comment by iiTsMatthew** [comment]
If the record is submitted to the non-flawless boards as well, then yes it would be the highest.

We don't often check if the record is already on the 'high round' leaderboard for example, that is up to the player to then submit it to that leaderboard also.

You're not stating where or how the leaderboards are inconsistencies, simply that it is flawless. 

I apologise but I do not have the time to check every single flawless record for every single game.

You haven't stated any records being illegitimate or otherwise, simply that you don't consider it legit without a reason.

If you pointed us to a game or record there is an issue, then we could go ahead and sort out that issue.

With the information you're giving us, I don't understand how you expect us to help you.

Kind Regards,
Matthew.

**Comment by Zannoeaze** [comment]
I'm saying y'all have changed the leaderboards and now certain records aren't consistent with other records that correspond with them. Didn't say any where illegitimate saying y'all have messed up the leaderboards with changing things cause it wasn't like this before. It took me like 15 mins going through different modes yesterday to see that. But if a staff member doesn't even notice the obvious inconsistencies when looking thought the different leaderboards than I'm wasting my time here and just won't use this site as a credible source anymore like many others are doing.

**Comment by iiTsMatthew** [comment]
You can't have an issue and expect people to have or see the same issues that you do.

I've been apart of this site' staff team for coming up on 4 years total now, so I've seen and gone through a lot of changes whether that be from staff, admins, leaders, the leaderboards and more, so if you have an issue with what's going on with the site, the leaderboards or otherwise, so please do let us know what your issues or concerns are so we can discuss the possibility of changing them. I don't know what your issue is if you don't tell me. I can't read your mind.

Kind Regards, 
Matthew.

**Comment by Zannoeaze** [comment]
So I have to do your job and go through the leaderboards and show you ever single inconsistent thing since y'all have changed the leaderboards (not trying to be smart or mean but come on now). Like I said, it wasn't like this not even a couple months ago. But since the leaderboards have been changed other records aren't consistent with each other. So whatever y'all did, just need to go back through and make sure records are right since y'all got rid of some. Now other records aren't accurate with being world record since some where removed by y'all

**Comment by iiTsMatthew** [comment]
I'm doing alot more then looking through leaderboards.

If you're not going to point us in the direction or explain what your issue is, then this is simply a pointless back and forth conversation.

If you ever man up and realise what your issues are, feel free to message me on Discord at Matthew <3#0665.

Kind Regards,
Matthew.
