### ISSUE TITLE
[Bug]: leaderboards 

### ISSUE THREAD

**Issue by Zannoeaze** [Zombies-World-Records/issue-tracker#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

So since you say I didn't tell you anything mathew I literally gave you an example where to find the inconsistencies in records. Flawless compared to non flawless. You shoved it aside saying the player didn't submit something but it wasn't like that till y'all changed the leaderboards so I why would I keep giving examples when you'll shove them off as the player not submitting something when it wasn't like that till y'all started removing records. If you can't understand or see the inconsistencies without me holding your hand through it then you are unfit to be staff and this site is doomed for a credible source if it keeps going in this trend of removing legit records and messing up the leaderboards. 

### Expected behaviour

Leaderboards 

### Steps to reproduce

Leaderboards 

### ZWR Account Link

Zannoeaze

**Comment by VincentFarris** [comment]
As far as I know, that has always been the case. What gets on the boards is based on the player submitting to those boards, if they don’t submit on those boards then they simply won’t be on them because they didn’t submit to that board. Also, attacking the staff isn’t going to get you anywhere, you’re not better than anyone.

**Comment by Zannoeaze** [comment]
Not attacking him just stating a fact. Also you didn't even read what I said I see. Y'all are stating a player must not have submitted to that category but they did and when y'all started removing records it messed up the leaderboards. I'm done arguing with people that don't even look at the leaderboards apparently and take down legit records that where up before and say nothing was submitted now. Hope y'all have a nice day in all honesty, but please review your leaderboards and staff for biased opinions cause it's looking like that's the case at this point with all the beating around the bush that I'm getting

**Comment by VincentFarris** [comment]
I did read what you said, the only reason we take down records is if they are found to be patched/cheated, or for the past 2 games(vanguard and CW) we refresh the boards because the game was updated which would make it unfair to other players try to go for records after that update occurred. You still haven’t stated specifically how the boards are “messed up” so until that we cannot help you because we don’t have enough information to help you. We aren’t beating around the bush because you haven’t given us a bush to beat around, you haven’t given us a specific instance of this problem happening, and where to find it.

**Comment by Zannoeaze** [comment]
I have stated where to look. You can look at bo4 for example. Game hasn't been patched but yet leaderboards had records removed and now are inaccurate on certain modes ie flawless compared to non flawless high rounds. And when I looked not even a couple months ago it matched up until records where removed. I really don't care at this point tho I just won't use this site anymore since I heard a new one is coming out

**Comment by VincentFarris** [comment]
As far as I can see, you don’t use this site in the first place because you don’t have a ZWR profile. If you can tell me which map and which players have this issue, I can help you better, but until then I can’t help you all that much.

**Comment by Cody-Orlando-spec** [comment]
The only records that were removed are cheated/patched or where the gameplay was taken down and no longer accessible. If you're talking about specific records, please tell us or link us what boards so we can investigate and fix issues. We are all completely volunteers and have lives outside of ZWR and do not have the time to sit through the entire site looking for small things like this. If you aware of specific boards, then how about telling us so we can rectify the issues. You've told us BO4, but you haven't said what map or record. Not very helpful, is it?

If you don't have anything constructive to say, then I will close this ticket. Stop creating tickets about the same issue and then being cryptic about what specific maps or records you're on about.

Regards,
Cody,
Development & Management Team.

**Comment by Zannoeaze** [comment]
I've heard and seen enough to see what's going on now on this site. y'all have a good one and don't get caught up 😉

**Comment by Cody-Orlando-spec** [comment]
Thank you for wasting our times. You complain yet can't actually tell us specific problems.

Have a good one.

/Closed
