### ISSUE TITLE
Thank you for wasting our times. You complain yet can't actually tell us specific problems.

### ISSUE THREAD

**Issue by Zannoeaze** [Zombies-World-Records/issue-tracker#19]
Thank you for wasting our times. You complain yet can't actually tell us specific problems.

Have a good one.

/Closed

_Originally posted by @Cody-Orlando-spec in https://github.com/Zombies-World-Records/issue-tracker/issues/18#issuecomment-1182275163_

**Comment by Zannoeaze** [comment]
I have and I see y'all have an agenda so good day and thanks for wasting everyones time with this site

**Comment by Drkiller99** [comment]
Okay, let's sort this out officially since there seems to be some confusion. 

If you seriously have issues with our website or how we run things and want to make suggestions on what you think is wrong, why it's wrong, etc then please fill out our community suggestion form that can be found [here](https://docs.google.com/forms/d/e/1FAIpQLSc-9mi8MF3PxxSHLfWoC779L_92pDBXPbT3-O_y4vyHyKHkMA/viewform). We are sorry for the way you are feeling right now and hope we can resolve this! 

Kind Regards,
ZWR Management.
