### ISSUE TITLE
[FEATURE]: Dear Zombie Records, I think the record list for first room in Cold War is kind of unfair as the people who get the record are also listed in “no Jug”, “no Power” and “No Perk”. In my Opinion it would be better if the records would be sorted out or the person gets only the record for which challenge, they wanted to do.

### ISSUE THREAD

**Issue by SiNeXxHayvan** [Zombies-World-Records/issue-tracker#25]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Drkiller99** [comment]
[Formatted]

Dear Zombie Records, 

I think the record list for first room in Cold War is kind of unfair as the people who get the record are also listed in “no Jug”, “no Power” and “No Perk”. In my opinion it would be better if the records would be sorted out or the person gets only the record for which challenge, they wanted to do.

I've pasted your suggestion above my message due to you pasting it all in the title, it will allow our whole team to just view it easier.

**Comment by iiTsMatthew** [comment]
Hi,

Thank you for your report.

Players are allowed to submit all of these records. If somebody played a game without turning the power on, not taking any perks, they are allowed to submit for No Jug as they didn't pick up Jug, for no perks as they didn't take any perks, and for no power as they didn't turn the power on. It is however not allowed to cross submit via sub-categories, for example, they would not be able to submit for all of those categories for classics and Megas for that category. 

Thank you for your suggestion once again.

If you require any more clarification on the matter please be sure to open a ticket in our discord at:  discord.gg/zwr.

Thank you for continuing to improve our website and use our service!
