### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by UTMUSK** [Zombies-World-Records/issue-tracker#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I had two world records on attack of the radio atctive thing. No Perks and No Jug with Only Fate cards. I got to round 49. It was there 3 hours ago, but when I checked again it was gone on both records. Idk why this happened but please help. Thanks

### Expected behaviour

NA

### Steps to reproduce

I have refreshed 

### ZWR Account Link

https://zwr.gg/players/VVRNVVNL/

**Comment by Cody-Orlando-spec** [comment]
Hi Utmusk,

After reviewing our records, your record was deleted due to your gameplay being removed after the submission was accepted. The requirement is that the video of the record is accessible at all times. Failure to do with will result in your submission being removed.

You are free to resubmit it, but ensure the gameplay is always accessible.

/Resolved
